---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux-gcc:
    name: linux-gcc
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get --yes install fluidsynth libfluidsynth-dev
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: autogen
        run: ./autogen.sh
      - name: Configure
        run: ./configure --prefix "$PWD/install"
      - name: Build
        run: make
      - name: Build tests
        run: make check
      - name: Install
        run: make install
      - name: Install check
        run: make installcheck
  linux-clang-with-lld:
    name: linux-clang-with-lld  # clang with LLVM's linker LLD
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get --yes install fluidsynth libfluidsynth-dev
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: autogen
        run: ./autogen.sh
      - name: Configure
        run: ./configure --prefix "$PWD/install" CC=clang CXX=clang++ LDFLAGS="-fuse-ld=lld"
      - name: Build
        run: make
      - name: Build tests
        run: make check
      - name: Install
        run: make install
      - name: Install check
        run: make installcheck
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: brew install automake fluid-synth
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: autogen
        run: ./autogen.sh
      - name: Configure
        run: ./configure --prefix "$PWD/install" CXXFLAGS="-std=c++11"
      - name: Build
        run: make
      - name: Build tests
        run: make check
      # install does not work yet, but seems less critical for now
  mingw-64:
    name: mingw-64
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up MSYS2
        run: |
          choco install msys2
          export MSYS2_PATH_TYPE=inherit
          export MSYS2_ARG_CONV_EXCL="*"
          export MSYS2_ENV_CONV_EXCL="GITHUB_PATH"
          echo "Adding MSYS2 to the PATH"
          echo "::add-path::C:\\tools\\msys64\\usr\\bin"
        shell: bash
      - name: Install libtoolize
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-libtool
        shell: bash
      - name: Build
        run: |
          ./configure
          make
        shell: bash
