---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux-gcc:
    name: linux-gcc
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get --yes install fluidsynth libfluidsynth-dev sordi gtk+2.0 libgtk2.0-dev libcairo2 lv2-dev
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
      - name: Build
        run: cmake --build build
  linux-clang-with-lld:
    name: linux-clang-with-lld  # clang with LLVM's linker LLD
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get --yes install fluidsynth libfluidsynth-dev sordi gtk+2.0 libgtk2.0-dev libcairo2 lv2-dev
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: >
          mkdir build && cd build &&
          cmake ..
          -DCMAKE_INSTALL_PREFIX=../install
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_FLAGS="-fuse-ld=lld"
          -DCMAKE_CXX_FLAGS="-fuse-ld=lld"
      - name: Build
        run: cmake --build build
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: brew install automake fluid-synth gtk+ cairo lv2
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
      - name: Build
        run: cmake --build build
        # install does not work yet, but seems less critical for now
  mingw-cross:
    strategy:
      matrix:
        compiler:
          - {bits: '32'}
          - {bits: '64'}
    name: mingw-${{matrix.compiler.bits}}-cross
    runs-on: ubuntu-latest
    steps:
      - name: Compile dependencies
        run: |
          cd /tmp
          wget https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2
          cd expat-2.5.0
          ./configure --host=i686-w64-mingw32 --prefix=/usr/i686-w64-mingw32/
          make
          sudo make install
          cd ..
          rm -rf /tmp/expat-2.5.0
      - name: Install dependencies
        run: |
          sudo apt-get install -y mingw-w64
          sudo add-apt-repository ppa:tobydox/mingw-w64
          sudo apt update
          sudo apt-get install -y fluidsynth-mingw-w64
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: >
          mkdir build && cd build &&
          PATH=/opt/mingw${{matrix.compiler.bits}}/bin:$PATH
          cmake ..
          -DCMAKE_INSTALL_PREFIX=../install
          -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/Ubuntu-MinGW-W64-${{matrix.compiler.bits}}.cmake
          -DCMAKE_PREFIX_PATH=/opt/mingw${{matrix.compiler.bits}}
      - name: Build
        run: cmake --build build
